### YamlMime:Yaml
ms.openlocfilehash: 679bfae77d86a466c88f8b69cb09b2d0681cbe4f
ms.sourcegitcommit: 592252864ff819d74c099ab4e63a0f8c6df88f6c
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/19/2019
ms.locfileid: "37046088"
php:
  preset: laravel
  disabled:
  - unused_use
  finder:
    not-name:
    - index.php
    - server.php
js:
  finder:
    not-name:
    - webpack.mix.js
css: true
